[colors-dark]
background=000000
foreground=cedaeb

## Normal/regular colors (color palette 0-7)
regular0=36283d  # black
regular1=71ADE9  # red
regular2=AB8CAE  # green
regular3=9EA0D3  # yellow
regular4=8BB8E9  # blue
regular5=E1B4CE  # magenta
regular6=cedaeb  # cyan
regular7=9098a4  # white

## Bright colors (color palette 8-15)
bright0=71ade9   # bright black
bright1=ab8cae   # bright red
bright2=e59db1   # bright green
bright3=9ea0d3   # bright yellow
bright4=8bb8e9   # bright blue
bright5=e1b4ce   # bright magenta
bright6=cedaeb   # bright cyan
bright7=fffefe   # bright white
